[package]
name = "adsp"
description = "Audio DSP library featuring a combinator environment for audio processing."
keywords = ["dsp", "audio"]
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
homepage = "https://github.com/SamiPerttu/adsp"
edition = "2018"

[dependencies]
generic-array = "0.14.4"
numeric-array = "0.5"
num-complex = "0.3"

[dev-dependencies]
cpal = "0.13"
anyhow = "1.0"

[features]
default = []
double_precision = []
forty_eight_khz = []
eighty_eight_point_two_khz = []
ninety_six_khz = []
one_hundred_seventy_six_point_four_khz = []
one_hundred_ninety_two_khz = []

[[example]]
name = "beep"
path = "examples/beep.rs"
