[package]
name = "fundsp"
description = "Audio processing and synthesis library with compact syntax."
keywords = ["dsp", "audio"]
license = "MIT OR Apache-2.0"
version = "0.0.9"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
homepage = "https://github.com/SamiPerttu/fundsp"
edition = "2021"

[dependencies]
generic-array = "0.14.4"
numeric-array = "0.5.2"
num-complex = "0.4.0"
rustfft = "6.0.1"
lazy_static = "1.4"
tinyvec = { version = "1.5", features = ["alloc"] }
rsor = "0.1.2"

[dev-dependencies]
cpal = "0.13"
anyhow = "1.0"

[features]
default = []

[[example]]
name = "beep"
path = "examples/beep.rs"

[[example]]
name = "peek"
path = "examples/peek.rs"
