[package]
name = "adsp"
version = "0.1.0"
authors = ["SamiPerttu <Sami.Perttu@gmail.com>"]
edition = "2018"

[dependencies]
num-complex = "0.3"
utd = { path = "../utd" }
typenum = "1.12"

[features]
default = []
double_precision = []
forty_eight_khz = []
eighty_eight_point_two_khz = []
ninety_six_khz = []
one_hundred_seventy_six_point_four_khz = []
one_hundred_ninety_two_khz = []
